development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username:  sample_app
  password:  password

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: sample_app
  password: password